### ISSUE TITLE
RSS Issue Tracker

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/bitcoinops.github.io#285]
- [ ] RSS link does not show on /en/publications/ 
- [ ] RSS link for en shows up on /ja/blog/
- [ ] RSS feed for ja language
